#!/usr/bin/env php
<?php declare(strict_types=1);

if(PHP_SAPI !== 'cli') exit; // exit if not executed from CLI

require_once 'vendor/autoload.php';

use Celyes\Ottonova\Calculator;
use Celyes\Ottonova\Printer\JsonPrinter;
use Celyes\Ottonova\Printer\ConsolePrinter;

// get command line flags and arguments

$options = getopt('', ["year::", "input::", "output::", "file::"]);


$input = $options['input'] ?? 'data.json';

$year = $options['year'] ?? '2020';

$output = $options['output'] ?? 'console';

$file = $options['file'] ?? 'vacations';

if(!file_exists($input)) { echo "\e[0;31mThe file you specified doesn't exist! quitting...\e[0m"; exit; }

switch($output) {
    case 'json':
        $printer = new JsonPrinter($file);
        break;
    default:
        $printer = new ConsolePrinter();
}

$data = json_decode(file_get_contents($input), true);

$calculator = new Calculator($year, $data, $printer);
$calculator->calculate()->output();